export const SEARCH_DATA = [
  { name: "Home", href: "/" },
  { name: "Solutions", href: "/solutions" },
  { name: "Network Solutions", href: "/solutions?tab=network" },
  { name: "Enterprise Mobility", href: "/solutions?tab=mobility" },
  { name: "Convergence Solutions", href: "/solutions?tab=convergence" },
  { name: "Collaboration Solutions", href: "/solutions?tab=collaboration" },
  { name: "Security Solutions", href: "/solutions?tab=security" },
  { name: "Enterprise Applications", href: "/solutions?tab=applications" },
  { name: "Managed Support", href: "/solutions?tab=support" },
  { name: "Cloud Solutions", href: "/solutions?tab=cloud" },
  { name: "Portfolio", href: "/portfolio" },
  { name: "Discover Us", href: "/discover-us" },
  { name: "Media", href: "/media" },
  { name: "Careers", href: "/careers" },
  { name: "Reach Us", href: "/reach-us" },
  { name: "Privacy Policy", href: "/privacy-policy" },
  { name: "Announcements", href: "/media/announcements" },
  { name: "Blogs", href: "/media/blogs" },
  { name: "Events", href: "/media/events" },
];
